from __future__ import annotations

from typing import Any


# Maps logical feature/toolset keys to VS workload/component IDs used in .vsconfig
COMPONENT_ID_BY_KEY = {
    "msbuild": "Microsoft.Component.MSBuild",
    "managed-desktop": "Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools",
    "mfc": "Microsoft.VisualStudio.Component.VC.MFC",
    "atl": "Microsoft.VisualStudio.Component.VC.ATL",
    "cpp-cli": "Microsoft.VisualStudio.Component.VC.CLI.Support",
    "cpp-v142": "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "cpp-v143": "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "windows-sdk-19041": "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "windows-sdk-22621": "Microsoft.VisualStudio.Component.Windows11SDK.22621",
}


def generate_vsconfig(build_input: dict[str, Any]) -> dict[str, Any]:
    components = list(build_input.get("visualStudio", {}).get("components") or [])
    # Ensure MSBuild present
    msbuild = COMPONENT_ID_BY_KEY["msbuild"]
    if msbuild not in components:
        components = [msbuild, *components]
    return {
        "version": "1.0",
        "components": sorted(set(components)),
    }


def _base_image_ref(agent: dict[str, Any], *, windows_base_name: str) -> str:
    """Prefer digest pins in prod; MVP placeholder digests use local tag refs."""
    image = agent["image"]
    digest = str(agent.get("digest") or "")
    tag = str(agent.get("tag") or windows_base_name or "latest")
    if "mvp" in digest.lower() or digest.endswith("mvp0001"):
        return f"{image}:{tag}"
    if digest.startswith("sha256:"):
        return f"{image}@{digest}"
    return f"{image}:{tag}"


def generate_dockerfile(build_input: dict[str, Any], *, profile_hash: str) -> str:
    agent = build_input["agentBase"]
    windows_base_name = str((build_input.get("windowsBase") or {}).get("name") or "latest")
    base_ref = _base_image_ref(agent, windows_base_name=windows_base_name)
    layout = build_input["visualStudio"]["layoutRelease"]
    template = build_input.get("templateVersion", "image-template-3")
    hash12 = profile_hash[:12]

    lines = [
        "# escape=`",
        "# Generated by Build Portal Image Factory — do not edit by hand",
        f"# profileHash={profile_hash}",
        f"# layoutRelease={layout}",
        f"# templateVersion={template}",
        "",
        f"ARG BASE_IMAGE={base_ref}",
        "FROM ${BASE_IMAGE}",
        "",
        'SHELL ["cmd", "/S", "/C"]',
        "",
        "COPY install-manifest.json C:\\ImageBuild\\install-manifest.json",
        "COPY profile.vsconfig C:\\ImageBuild\\profile.vsconfig",
        "COPY scripts C:\\ImageBuild\\scripts",
        # Offline layout + installers are staged into the build context by the factory agent.
        "COPY layout C:\\Layout",
        "COPY installers C:\\Installers",
        "",
        "ENV IMAGE_FACTORY_LAYOUT_ROOT=C:\\Layout",
        "ENV IMAGE_FACTORY_INSTALLER_ROOT=C:\\Installers",
        "",
        "RUN C:\\ImageBuild\\scripts\\Install-BuildEnvironment.cmd",
        "",
        "RUN powershell.exe -NoProfile -NonInteractive `",
        "    -File C:\\ImageBuild\\scripts\\Validate-Environment.ps1",
        "",
        f'LABEL company.build.profile-hash="{hash12}"',
        f'LABEL company.build.template-version="{template}"',
        f'LABEL company.build.layout-release="{layout}"',
        "",
    ]
    return "\n".join(lines)


def _netfx_logical_version(resolved_version: str) -> str:
    """Map installer resolvedVersion back to catalog logical framework id."""
    if resolved_version.startswith("4.8."):
        return "4.8"
    if resolved_version == "4.6.0":
        return "4.6"
    return resolved_version


def generate_install_manifest(build_input: dict[str, Any]) -> dict[str, Any]:
    """Manifest consumed by Install-BuildEnvironment.cmd on the Factory host."""
    packs = list(build_input.get("dotnetFrameworkTargetingPacks") or [])
    # Logical frameworks for capability matching (not installer patch versions).
    logical_frameworks = sorted(
        {
            _netfx_logical_version(str(item.get("version") if isinstance(item, dict) else item))
            for item in packs
        }
    )
    return {
        "windowsBase": build_input["windowsBase"],
        "agentBase": build_input["agentBase"],
        "visualStudio": build_input["visualStudio"],
        "dotnetFrameworkTargetingPacks": packs,
        "dotnetFrameworks": logical_frameworks,
        "dotnetSdks": build_input.get("dotnetSdks") or [],
        "windowsSdks": build_input.get("windowsSdks") or [],
        "cppToolsets": build_input.get("cppToolsets") or [],
        "features": build_input.get("features") or [],
        "customSdks": build_input.get("customSdks") or [],
        "installScriptVersion": build_input.get("installScriptVersion"),
        "validationSuiteVersion": build_input.get("validationSuiteVersion"),
    }
